#!/usr/bin/env python3
"""
Generalized NOP of every CBNZ-w0 in proton9's winevulkan.dll that
gates entry into a loader-thunk `_assert("!status && \"<funcname>\"")`
handler.

Why generalized: the surgical 2-site patch
(`patch_winevulkan_proton9_ds3.py`) suppressed the vkCreateShaderModule
wassert and let DS3 progress past the previous crash trigger, but a
downstream wassert on vkCreateComputePipelines fired next. The cause
(ARM64EC loader-thunk envelope returns non-zero NTSTATUS even when
Vulkan returned VK_SUCCESS — see state_ds3.md 2026-04-27 cause-
confirmed section) is universal: every wrapper generated by wine's
make_vulkan from loader_thunks.c has the same `BLR vk -> CBNZ w0 ->
assert` skeleton. Need to disarm them all.

Why not blanket BLR-to-_assert sweep: that's exactly what
`patch_winevulkan_assert.py` does, and on proton9 it patches 711 BLRs
including non-loader-thunk asserts and breaks loading entirely
(failed_attempts.md, 2026-04-25). This script is narrower: it ONLY
matches the compiler-emitted loader-thunk handler signature
(ADRP+ADD-into-x0 of a `!status && "..."` string in .rdata), then
NOPs the CBNZ w0 that branches to that handler.

Algorithm:
  1. Find every `!status && "..."` ASCII string in .rdata. The format
     is auto-generated by make_vulkan and only appears as loader-
     thunk assertion messages (684 strings; we drop 2 that aren't
     followed by ' && "').
  2. For each string, find the ADRP-x0 + ADD-x0 pair in .text that
     loads its address. That's the second instruction of an assert
     handler.
  3. The first instruction of the handler (one BEFORE step 2) is an
     ADRP that loads the IAT page for `_assert`. The CBNZ that gates
     entry branches to either the IAT-load ADRP (offset -4) or the
     ADRP-x0 itself.
  4. Scan .text for CBNZ w0 instructions; if the branch target lands
     on a known handler entry, NOP the CBNZ.

Effect: control falls through to the success return path that
restores x30 and reloads the actual VkResult from stack, ignoring the
NTSTATUS quirk.

Verified on: proton9 winevulkan.dll md5 82245152ee8472c8d98080e7a7c15a14
(610304 bytes). Expects 682 NOP sites.
"""
import struct
import sys
import hashlib

NOP = 0xD503201F
EXPECTED_MD5 = '82245152ee8472c8d98080e7a7c15a14'
EXPECTED_SIZE = 610304
EXPECTED_HITS = 682  # one per loader-thunk function generated by make_vulkan


def find_handler_x0_pcs(data, image_base, txt_va, txt_size, txt_raddr):
    """Map: PC of ADRP-x0 in handler -> runtime address of `!status && "..."` string."""
    handlers = {}
    for off in range(0, txt_size - 8, 4):
        foff = txt_raddr + off
        pc = image_base + txt_va + off
        ins = struct.unpack_from('<I', data, foff)[0]
        # ADRP into x0
        if (ins & 0x9F000000) != 0x90000000: continue
        if (ins & 0x1f) != 0: continue
        immlo = (ins >> 29) & 3; immhi = (ins >> 5) & 0x7ffff
        imm = (immhi << 2) | immlo
        if imm & 0x100000: imm |= ~((1 << 21) - 1)
        page = (pc & ~0xfff) + (imm << 12)
        # Next instruction must be ADD into x0 from x0
        ins2 = struct.unpack_from('<I', data, foff + 4)[0]
        if (ins2 & 0xFFC00000) != 0x91000000: continue
        if ((ins2 >> 5) & 0x1f) != 0 or (ins2 & 0x1f) != 0: continue
        imm12 = (ins2 >> 10) & 0xfff
        str_runtime = page + imm12
        str_off = str_runtime - image_base
        if str_off < 0 or str_off + 12 > len(data): continue
        # Verify it's a loader-thunk assertion message
        if data[str_off:str_off+12] == b'!status && "':
            handlers[pc] = str_runtime
    return handlers


def patch(in_path, out_path):
    raw = open(in_path, 'rb').read()
    if len(raw) != EXPECTED_SIZE:
        sys.exit(f'unexpected size {len(raw)}, expected {EXPECTED_SIZE}')
    md5 = hashlib.md5(raw).hexdigest()
    if md5 != EXPECTED_MD5:
        sys.exit(f'unexpected md5 {md5}, expected {EXPECTED_MD5}')
    data = bytearray(raw)

    # PE / section walk
    pe_off = struct.unpack_from('<I', data, 0x3c)[0]
    coff = pe_off + 4
    _, nsec, _, _, _, opthdr_size = struct.unpack_from('<HHIIIH', data, coff)
    opt_off = coff + 20
    image_base = struct.unpack_from('<Q', data, opt_off + 24)[0]
    sec_off = opt_off + opthdr_size
    txt = None
    for i in range(nsec):
        s = sec_off + 40 * i
        name = data[s:s+8].rstrip(b'\x00').decode('latin1')
        vsize, vaddr, _, raddr, _ = struct.unpack_from('<IIIII', data, s+8)
        if name == '.text':
            txt = (vaddr, vsize, raddr)
            break
    if txt is None: sys.exit('.text section not found')
    txt_va, txt_size, txt_raddr = txt

    handlers = find_handler_x0_pcs(data, image_base, txt_va, txt_size, txt_raddr)
    print(f'found {len(handlers)} loader-thunk assert handlers')

    # CBNZ target may land on the handler's first instruction (ADRP IAT-page,
    # one before our ADRP-x0 detection) OR on the ADRP-x0 itself.
    targets = {}
    for hpc, sr in handlers.items():
        for delta in (-4, 0):
            targets[hpc + delta] = (hpc, sr)

    hits = 0
    for off in range(0, txt_size - 4, 4):
        foff = txt_raddr + off
        pc = image_base + txt_va + off
        ins = struct.unpack_from('<I', data, foff)[0]
        # CBNZ w-reg (sf=0): top byte 0x35
        if (ins & 0xFF000000) != 0x35000000: continue
        if (ins & 0x1f) != 0: continue  # only Rt = w0
        imm19 = (ins >> 5) & 0x7ffff
        if imm19 & 0x40000: imm19 |= ~((1 << 19) - 1)
        target = pc + imm19 * 4
        if target not in targets: continue
        struct.pack_into('<I', data, foff, NOP)
        hits += 1

    print(f'NOPed {hits} CBNZ w0 sites (expected ~{EXPECTED_HITS})')
    if hits != EXPECTED_HITS:
        print(f'WARNING: hit count diverged from expected; review before deploying')
    open(out_path, 'wb').write(data)
    out_md5 = hashlib.md5(bytes(data)).hexdigest()
    print(f'wrote {out_path} (md5 {out_md5})')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().split('\n\n')[-1])
    patch(sys.argv[1], sys.argv[2])
