#!/usr/bin/env python3
"""
Surgical NOP of the two CBNZ branches in proton9's winevulkan.dll that
gate the `_assert("!status && \"vkCreateShaderModule\"")` call sites.

Why surgical, not blanket: patch_winevulkan_assert.py NOPs every BLR-to-
_assert in the binary. Run on Pepelespooder wine-10's 2.74 MB binary it
works; run on proton9's 610,304 B binary it patches 711 BLRs and breaks
loading entirely (failed_attempts.md, 2026-04-25).

This patch touches 8 bytes total: the two `CBNZ w0, <error_handler>`
instructions that branch to the assert-call sites. The wrapper layout
generated by make_vulkan is:

    BLR x8                      ; call the underlying vk function
    CBNZ w0, <error_handler>    ; ← NOP this
    LDR w0, [x31, #0x28]        ; success path: reload return value
    LDR x30, [x31, #0x30]
    ADD x31, x31, #0x40
    RET
  <error_handler>:
    ADRP/ADD x0, "!status && \"<funcname>\""
    LDR  x8, [_assert IAT]
    ADRP/ADD x1, file
    MOVZ w2, line
    BLR  x8
    BRK  #1

NOPing the CBNZ ignores the NTSTATUS, falls through to the success
return — which is exactly what an NDEBUG build would do. We never load
the assert args, never call _assert, never reach the BRK.

Cause confirmed in state_ds3.md 2026-04-27: vk_gc probe shows the wrapper
returned VK_SUCCESS for all 688 vkCreateShaderModule calls; the NTSTATUS
that trips the assert is from the ARM64EC loader-thunk envelope, not the
VkResult.

Tested on: files/proton9/lib/wine/aarch64-windows/winevulkan.dll
md5 82245152ee8472c8d98080e7a7c15a14 (610304 bytes).

Usage: patch_winevulkan_proton9_ds3.py INPUT.dll OUTPUT.dll
"""
import struct
import sys

# Two call sites for "!status && \"vkCreateShaderModule\"" in proton9's
# 82245152 winevulkan.dll. Each site has the assert args (message string
# at 0x18002b5c8 / 0x180036f98, file string + line=3275) and a CBNZ that
# guards entry. NOPing the CBNZ short-circuits the assert path.
NOP = 0xD503201F
SITES = [
    (0xb9d0,  0x350000a0, 'site #1: thunk pre-asserting "!status && \\"vkCreateShaderModule\\""'),
    (0x1b010, 0x350000a0, 'site #2: thunk pre-asserting "!status && \\"vkCreateShaderModule\\""'),
]
EXPECTED_MD5 = '82245152ee8472c8d98080e7a7c15a14'
EXPECTED_SIZE = 610304


def patch(in_path, out_path):
    import hashlib
    raw = open(in_path, 'rb').read()
    if len(raw) != EXPECTED_SIZE:
        sys.exit(f'unexpected size {len(raw)}, expected {EXPECTED_SIZE} '
                 f'(this script targets proton9 winevulkan.dll only)')
    md5 = hashlib.md5(raw).hexdigest()
    if md5 != EXPECTED_MD5:
        sys.exit(f'unexpected md5 {md5}, expected {EXPECTED_MD5}')
    data = bytearray(raw)
    for foff, expected_ins, label in SITES:
        actual = struct.unpack_from('<I', data, foff)[0]
        if actual != expected_ins:
            sys.exit(f'foff 0x{foff:x}: expected 0x{expected_ins:08x}, '
                     f'found 0x{actual:08x} — binary changed, abort')
        struct.pack_into('<I', data, foff, NOP)
        print(f'patched foff=0x{foff:x}: 0x{expected_ins:08x} -> 0x{NOP:08x}  ({label})')
    open(out_path, 'wb').write(data)
    out_md5 = hashlib.md5(bytes(data)).hexdigest()
    print(f'wrote {out_path} ({len(data)} bytes, md5 {out_md5})')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip().split('\n\n')[-1])
    patch(sys.argv[1], sys.argv[2])
